version: "3.8"

services:

  db:
    image: postgres:15.1-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 3

  migration:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/todolist/.env
    command: python manage.py migrate

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    volumes:
      - ./:/todolist
    restart: on-failure
    ports:
      - "${API_PORT:-8000}:8000"

  frontend:
    image: sermalenk/skypro-front:lesson-36
    restart: on-failure
    depends_on:
      - api
    ports:
      - "${FRONTEND_PORT:-80}:80"