# Generated by Django 4.1.5 on 2023-01-26 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='описание')),
                ('due_date', models.DateField(blank=True, default=None, null=True, verbose_name='дата выполнения')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'к выполнению'), (2, 'в процессе'), (3, 'выполнено'), (4, 'архив')], default=1, verbose_name='статус')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'низкий'), (2, 'средний'), (3, 'высокий'), (4, 'критический')], default=2, verbose_name='приоритет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goalcategory', verbose_name='категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'цель',
                'verbose_name_plural': 'цели',
            },
        ),
    ]
